### ISSUE TITLE
Mempool Space backend crashes when bitcoind's mempool gets very large

### ISSUE THREAD

**Issue by wiz** [raspiblitz/raspiblitz#2008]
### Background

On a Raspberry Pi with 4GB or more of RAM, the bitcoin.conf setting for `maxmempool` is increase to 512MB.

### Issue

The increased size of the bitcoind mempool requires the mempool.space backend to utilize more RAM. Additionally, the mempool.space integration on RaspiBlitz reduces the setting for the max heap size of mempool backend's nodejs process from 4GB to 2GB. The combination of these two configuration settings causes the mempool.space backend to crash when the bitcoin mempool gets very full (over 400MB).

### Fixes

* Reduce the bitcoin.conf maxmempool setting back to 300MB as default
* Optimize the memory usage inside the mempool.space backend so 2G heap size works without crashing

**Comment by wiz** [comment]
> Optimize the memory usage inside the mempool.space backend

Simon optimized the memory usage in the mempool backend in https://github.com/mempool/mempool/pull/342 and we will prepare a `v2.1.2` hotfix release containing that patch - from our testing it should now work fine with only 2G heap size

**Comment by rootzoll** [comment]
faxes and updates merged

**Comment by rootzoll** [comment]
OK first test looks good :) closing this issue ... final testing for release on: #2076

**Comment by ghost** [comment]
It has been crashing for me and i suspect this is culprit, I have 700mb mempool on bitcoind. 
![image](https://github.com/user-attachments/assets/a11d3f08-a3a9-42da-95b0-9f3c4fe01619)

**Comment by ghost** [comment]
Well I put this in my compose.yml for the api

```
  environment:
      NODE_OPTIONS: --max_old_space_size=4096
```

And so far I am not seeing the messages anymore. Will update if bad things happen. I have 8GB RAM and I am actually on an x86 mini PC not a Pi.

**Comment by ghost** [comment]
Came to say that after applying some fixes it has never ran better.

I increased the node mem heap to 4096, I am using mariadb:latest as the db docker image and I am forcing the db collation to utf8 and it is running like a dream, has never ran better, this is on a 4 core J3160 celleron with 8GB of DDR3 ram.

Oh and my bitcoind has 700mb of mempool which is what I am led to believe was causing node to exceed its 2048 heap.

Below docker compose, put in your own IP/Ports and user/pass for your setup.

```
services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: api
    image: mempool/frontend:latest
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    command: ./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'
    ports:
      - 127.0.0.1:8080:8080 # I am using nginx to expose this more broadly
  api:
    environment:
      #MEMPOOL_BACKEND: none
      MEMPOOL_BACKEND: electrum
      ELECTRUM_HOST: 10.x.x.x
      ELECTRUM_PORT: "xxxx"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: 10.x.x.x
      CORE_RPC_PORT: "xxxx"
      CORE_RPC_USERNAME: xxxx
      CORE_RPC_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      DATABASE_ENABLED: "true"
      DATABASE_HOST: db
      DATABASE_DATABASE: mempool
      DATABASE_USERNAME: mempool
      DATABASE_PASSWORD: mempool
      STATISTICS_ENABLED: "true"
      NODE_OPTIONS: --max_old_space_size=4096
    image: mempool/backend:latest
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    command: ./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh
    volumes:
      - ./data:/backend/cache
  db:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: makeyourownrootpassword
    image: mariadb:latest
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
networks: {}
```
![image](https://github.com/user-attachments/assets/0d7ddb2a-c5a7-44ac-8625-2ff35a7c1706)
